name: UI Tests

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'cesargarrido/stabilitymatrix' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test StabilityMatrix.UITests
